from app.bll.service import *
from app.presentation.controller.orders.bank_controller import BankController
from app.presentation.controller.orders.cash_account_controller import CashAccountController
from app.presentation.controller.orders.cashier_controller import CashierController
from app.presentation.controller.orders.deposit_contract_controller import DepositContractController
from app.presentation.controller.orders.credit_contract_controller import CreditContractController
from app.presentation.controller.orders.employee_controller import EmployeeController
from app.presentation.controller.orders.manager_controller import ManagerController
from app.presentation.controller.orders.user_controller import UserController

bank_controller = BankController(bank_service, user_service, cash_account_service)
cash_account_controller = CashAccountController(cash_account_service, deposit_contract_service, credit_contract_service)
cashier_controller = CashierController(cashier_service)
deposit_contract_controller = DepositContractController(deposit_contract_service)
credit_contract_controller = CreditContractController(credit_contract_service)
employee_controller = EmployeeController(employee_service)
manager_controller = ManagerController(manager_service, employee_service, deposit_contract_service, credit_contract_service)
user_controller = UserController(user_service)
